### PR TITLE
Default timeout for mysql and rabbit is too large

### PR DESCRIPTION
**Pull request by damjanek**

### CODE REVIEW

**Comment by cloudlab-autobuild** [comment]
Can one of the admins verify this patch?

**Comment by pupapaik** [comment]
Those timeouts are taken from Fuel deployment configuration files. Can someone confirm? Because Fuel 8 uses exactly same values.

**Comment by SwannCroiset** [comment]
> Those timeouts are taken from Fuel deployment configuration files. Can someone confirm? Because Fuel 8 uses exactly same values.

you're right for mysql w/ mos9:
``````

**Comment by cznewt** [comment]
So do we have some haproxy expert's to have opinion on this - reason for these times?

**Comment by cloudlab-autobuild** [comment]
Can one of the admins verify this patch?

**Comment by damjanek** [comment]
Reason for 300s or 48h and 28001s?

**Pull request merged**
